site_name: {{cookiecutter.project_name}}
nav:
  - Home: /
  - Documentation:
    - Quickstart: docs/01-quickstart.ipynb
  - Reference: reference.md
plugins:
  - search
  - mkdocstrings:
      watch:
        - src
  - mkdocs-jupyter
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
theme:
  name: material
  palette:
    primary: white
    accent: purple
markdown_extensions:
  - pymdownx.arithmatex
  - footnotes
  - codehilite:
      linenums: true
# repo_url: https://github.com/boukepostma/cookiecutter-data-science
# edit_uri: edit/master/docs/docs